### ISSUE TITLE
Unarchive

### ISSUE THREAD

**Issue by markterm** [migibert/terraform-role#2]
Should the unarchive task not have copy=no ?

Otherwise as per http://docs.ansible.com/ansible/unarchive_module.html it tries to copy the zip first from the local system, whereas it has just been downloaded to the target system by get_url.

(btw, thanks for sharing this role)

**Comment by migibert** [comment]
My bad, I already had this issue on another role and forgot to backport the fix here.

Thanks for your feedback!
