### ISSUE TITLE
Not working on RedHat.

### ISSUE THREAD

**Issue by ghost** [migibert/terraform-role#5]
Recommand to read:
https://serverfault.com/questions/587727/how-to-unify-package-installation-tasks-in-ansible

https://github.com/migibert/terraform-role/blob/2f2d9a255b653aa10e45754e1d9e0c4009b3e59a/tasks/main.yml#L25

**Comment by ghost** [comment]
Agreed, fix actually requires changing one word in tasks -> from apt to package 
Other than that, great role, thank You for sharing

**Comment by migibert** [comment]
Thanks for your proposition, I will take a look asap!
